### ISSUE TITLE
Add London/Birmingham energy performance certificate (EPC) data

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-london#126]
@iagw has uploaded data at: https://github.com/iagw/colouring-cities

The dataset is split into two parquet files – which have the GLA (Greater London Authority) local authorities and the West Midlands Combined Authority local authorities.

The data has been reduced to the following columns:

```
importColumns = ['CURRENT_ENERGY_RATING',
                 'LODGEMENT_DATE',
                 'FLOOR_LEVEL',
                 'CONSTRUCTION_AGE_BAND',
                 'UPRN',
                 'EPCDatafromFile',
                 'TOID']
```

### Prerequisite

- [ ] colouring-cities/colouring-core#815

### Task

- [ ] Create script(s) to add the above EPC data fields into the Colouring London database (i.e. add to buildings table via linking on TOID)
    - **Note:** we'll want the edits to be made in the usual way so they show up in the edit history - see colouring-cities/colouring-core#815 
- [ ] Colour buildings based on the colouring scheme used by the energy performance certificates themselves, i.e. the value of `'CURRENT_ENERGY_RATING'` (see code snippet that has colours from the mapbox site for Birmingham below)

### Note 

- We may have to test with just London data, until there is an available testing environment for "Colouring Birmingham" or as part of "Colouring Britain"
- Before rolling out to production, we may want to come up with a way to differentiate computational edits vs manual - see comments in colouring-cities/colouring-core#815 

### Birmingham mapbox colours

```
'circle-color': [
    "match",
    [
        "get",
        "current_energy_rating"
    ],
    "A",
    "hsl(214,45%,49%)",

    "B",
    "hsl(150,86%,28%)",

    "C",
    "hsl(87,53%,56%)",

    "D",
    "hsl(58,87%,58%)",

    "E",
    "hsl(38,91%,59%)",

    "F",
    "hsl(20,87%,56%)",

    "G",
    "hsl(357,82%,53%)",
    "hsla(0, 0%, 0%, 0)",
],
```

**Comment by polly64** [comment]
@MKIM1008 let's talk re a comparison of loughboough and london epc age data with other age data we are generating
