### ISSUE TITLE
jan 2024 summary of outstanding feature requests for partner collaboration and closure of old issues

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#257]
- [ ] **Split screen option** colouring-cities/colouring-core#5 Use open streetmap. See National Library Scotland example here works very well. https://maps.nls.uk/geo/explore/side-by-side/#zoom=5.0&lat=56.00000&lon=-4.00000&layers=1&right=ESRIWorld 

- [ ] colouring-cities/colouring-core#11 colouring-cities/colouring-core#81

- Do we display labels as a separate layer, and enable customising of Night/Light basemap styles?  colouring-cities/colouring-core#11
- Restore map location. Do we need to do this?  colouring-cities/colouring-core#81
- Look into OS Open Roads, nominatim or similar to populate building street names with spatial analysis 
    nearest-line-to-polygon or centroid should catch many cases
    street-corner-cases (prefer main road?)

- [ ] colouring-cities/colouring-core#18
    there are many interesting questions which are hard to answer with a single-layer visualisation
    e.g. show libraries built before 1900; residential buildings over 4 storeys high; ...
Suggestion:
    explore ways to filter/search/select against multiple fields, generating visualisations (or tables?)
    access through 'advanced search' user interface Problem:  

- [ ] colouring-cities/colouring-core#24
- Polygon should be split (currently represents multiple buildings with a single outline)
- Polygons should be joined (currently represent a single building with multiple outlines)
- Polygon is missing where there is a building
- Polygon is present where there is no building
- Polygon shape doesn't match current building

- [x] colouring-cities/colouring-core#29 

    API endpoint for overall contributions in the last 7 days/30 days/all time
    Statistics page with initial notice: "123 contributions in the last 7 days/30 days/all time"

Hourly/daily/monthly:
    page views (home, content, building/cat)
    logins
    registrations

- [ ] colouring-cities/colouring-core#62

Collaborative work to improve user login, authentication, sign up page  etc would be helpful
For reference (via https://github.com/colouring-cities/colouring-core/issues/61#issuecomment-522516290)
Alternative to reset password (or password login at all)
- Request login link (email address form)
- Generate token
- Send email
- Validate token and login
- Expire tokens
    https://www.lfgss.com/ have a nice example of email/temporary PIN login
    built with https://microco.sm/ forum software
        API is open source https://github.com/microcosm-cc/microcosm/ (Go) as is the web client https://github.com/microcosm-cc/microweb (Python/Django)
        with nice one-page API usage documentation http://microcosm-cc.github.io/

- [ ] User self identification colouring-cities/colouring-core#64 
Allow users to add themselves to a user type category (enables stats/leaderboards). Should be optional at sign up
user_category table+reference
Pick category at sign-up
Show category on my-account
e.g  Individual contributors; Schools; Colleges/University students; Researchers; Voluntary/Non-profit organisations
    Business/ Industry; Local authorities; Central Government Departments/Agencies; Other.

'If you would like help in our audience survey so we may improve our site please tick the sector/sectors of relevance and areas of particular interest here (optional)

Audiences
Community
Local government
Central government
Academia
Construction industry/built environment professionals
Open data community
Heritage/conservation volunteers
Historical research (outside academia)
Other

Area/s of application/interest
Community health and well-being
Housing policy, management and delivery
National/regional or local planning policy/management and delivery
Heritage and conservation delivery
Sustainable construction delivery
Construction industry/property market analysis
Energy reduction delivery
Academic research - energy, housing, heritage, planning, lifespan/survival, other
Data science
Open Data
Primary/secondary education
Tertiary education and/or lifelong learning
Urban economics
Other
- [ ] **Mobile app** colouring-cities/colouring-core#139

Add button to map interface which zooms to current position - do we already have this?

Use case: I'm out and about and want to edit the building I'm stood by, interface jumps me to this position on the map.
Leaflet geolocation plugins: https://leafletjs.com/plugins.html#geolocation - at a quick glance, [domoritz/leaflet-locatecontrol](https://github.com/domoritz/leaflet-locatecontrol) ([demo](https://www.domoritz.de/leaflet-locatecontrol/demo/)) looks good.

colouring-cities/colouring-core#207 

adaptability rting, Collect dates for change of land use/adaptation.

Arising from discussion use case around mosques - i.e. house to mosque occurred, including when defunct as mosque. tree preservation orders 

colouring-cities/colouring-core#239 hover or click input label to show hint (remove existing hint link)

reported use case for mosques would like to include:

   Mosques 'Purpose built' or 'Converted '
    'Denomination'

Increase zoom level?

colouring-cities/colouring-core#269

<img width="597" alt="Screenshot 2023-12-27 at 15 06 21" src="https://github.com/colouring-cities/colouring-core/assets/42236514/7989b5ba-bdf3-43f9-bc43-5fafd12770f6">

 colouring-cities/colouring-london#194 monitoring and moderation
 Team membership thought capture colouring-cities/colouring-london#195
 Meta issue - open design process colouring-cities/colouring-london#196 
 API: Retrieve all edits by user colouring-cities/colouring-london#200 
 Feature tour / introduction colouring-cities/colouring-core#336 
 API: swagger doc and definition for GET buildings colouring-cities/colouring-london#198 
 Replace deprecated componentWillReceiveProps colouring-cities/colouring-london#199 
Allow temporary blocking and permanent banning of users  colouring-cities/colouring-core#518 
      colouring-cities/colouring-core#518 allow temorary blocking of users DYNAMICS colouring-cities/colouring-london#87 
 SHOWCASE SECTION/COP 26/'DATA INSIGHTS SECTION' colouring-cities/colouring-core#644 
 Add reward badges for contributors colouring-cities/colouring-core#646 
 Contacting the project/blog colouring-cities/colouring-core#707 

colouring-cities/colouring-core#269

Once we have collected data on a building which infers it is residential and 19th Century we could then set a database trigger that says the wall material is solid masonry and timber frame based on prior research, the feature could apply to many categories based on pre defined rules which are then transposed into a database trigger

checking on different mach9nes/mobiles

Prepare user friendly technical info page ready for upload
https://github.com/colouring-cities/colouring-core/issues/38
Create short how-to use this site animation using open software and able to be easily added to /adjusted over time
Test usability of sign-up and code of conduct make recommendations for improvements if required
https://github.com/colouring-cities/colouring-core/issues/391
Make recommendations for simplification of discussion page
https://github.com/colouring-cities/colouring-core/issues/270
Prepare new leaderboards spec TR for schools, historic environment bodies, commercial sector
https://github.com/colouring-cities/colouring-core/issues/48
Prepare first draft for blog page to announce new features as grants (as rec by TR)
Create copyright free diagrams for roof forms and typologies for the 'Size and shape' category' to add to dropdown
Prepare design for Showcase page as
https://github.com/colouring-cities/colouring-core/issues/571
Show stats (see Dom) to allow easy measurement for funders/interest parties on user numbers
https://github.com/colouring-cities/colouring-core/issues/65
Look at issue os schools sign up and under 13 sign up with guardian to discuss with TR
https://github.com/colouring-cities/colouring-core/issues/385
Sign up for ODI endorsement https://github.com/colouring-cities/colouring-core/issues/528 and add ODI landbook
https://github.com/colouring-cities/colouring-core/issues/482
Work with PH and LJ to improve elegance of page design
https://github.com/colouring-cities/colouring-core/issues/495

    Look at if we can collect optional information on kinds of groups users are coming from to ensure we including as wide an audience as possible. I think this is best done perhaps when signing up for leaderboard

https://github.com/colouring-cities/colouring-core/issues/467

seven key conclusions from NUA CASA report as follows

    High quality system architecture critical to meeting NUA goals though digital delivery? How can this be ensured
    How do you keep the system sustainable? How do you keep data input up-to-date? and how do you manage automatic input of data from process?
    How do you address institutional fear in the UK of data collection and analysis?
    How does data capture become part of the day to day operations?
    What is the bare minimum of activity in data collection and analysis to be successful?
    How important is political support and leadership –( and what issues might exist around this)?
    How do you = develop a strategy that accommodates fir the fact that new approaches will take time to deliver?

I am writing up how Colouring Cities strategy addresses each as part of PhD final chapter and will post here (other than for point one on the technical/open source side) and would be good we could begin to draft a future paper on this

**Comment by matkoniecz** [comment]
should we keep it open? or close as old news?
