### ISSUE TITLE
Update Colouring London 2016 OSMM polygons and facilitate automatic updating

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-london#722]
### Tasks

- [x] Request to download the data from [here](https://www.ordnancesurvey.co.uk/business-government/licensing-agreements/data-exploration)
    - [x] Download data once request received
- [x] Document existing DB setup with latest OS data #798 
- [x] Create script for adding the new data to db (see below comment) & document the script that does this update, test in a dev environment. Set up a db from dump file and then update it with new script.
- ~~Come up with a way in the app code to view older versions (previous OS release years or historical map years), test in dev~~ #751 <- lets do this separately later
- [x] #804
- [x] Roll out the update to CL servers

## Linked

- #817
- #818

**Comment by edwardchalstrey1** [comment]
### Facilitate automatic updating

Script should:

- [ ] Add polygons from new OS data to geometries table that have **new** TOIDs i.e. are not already in the db & create new building record to match, with best guess build date of today
- [ ] Check if any of the features (e.g. lat/lon) in the update (the new geometries) match one of our pre-existing TOIDs (pre-update geometries) but have a different geometry/shape - in which case mark the old one as valid to today and add the new one as valid from today, keep both linked to the existing building record (so don't have a new building record when this is the case)
- [ ] Check if any of our pre-existing TOIDs are no longer present in the update - in which case mark as valid to today, and assume the building no longer exists, with best guess demolition date of today
