### ISSUE TITLE
Facilitate building attribute data upload for Land use

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-london#724]
### Tasks

- [x] Change 'Unclassified presumed residential' on dropdown to 'Unclassified presumed non-residential'
- [x] Add full title of 'Unclassified, presumed non-residential' to Land use key. can be on 2 lines
- [x] Using code from Age data section, if applicable, add a land use source dropdown in the Current Use section to include the following options
    - Expert/personal knowledge of building
    - Online streetview image
    - Open planning authority dataset
    - Open property tax dataset
    - Open housing dataset
    - Open address dataset
    - Other
- when dropdown completed prompt 'source' box to appear in which url links for all options except first two (of the above) can be added.  
    - [x] Add source box
    - [ ] Make it only appear when correct options selected - should we do this for Age too?
- [x] Only permit text beginning with https in source boxes- for all Colouring platform categories (ed let's discuss security here too - as done for Age category
- [x] Add 'Residential (verified)' class and  also change current 'Residential' to Residential (unverified)' on  land use dropdown and colour key

### Linked tasks (added to [milestone](https://github.com/colouring-cities/colouring-london/milestone/17))

- #816
- #812
- #814
- #815

**Comment by polly64** [comment]
- [ ] Change 'Unclassified presumed residential' on dropdown to 'Unclassified presumed non-residential'
- [ ] Add full title of 'Unclassified, presumed non-residential' to Land use key. can be on 2 lines
- [ ] Change text disclaimer to read xxxxxx
- [ ]  Suggest/implement way of colouring a) Residential garden buildings' and b) Hotels nd adding to the key. We are now able to record these using the dropdowns but we are still not able to visualise them as they are all showing as blue/residential. We need to differentiate in some way
- [ ] Using code from Age data section add a source dropdown in the Current Use section to read as follows:
Expert/personal knowledge of building
Online streetview image
Planning authority data
Ordnance Survey data
Valuation Agency data
Other
- [ ] Activate verification copy too (as for all categories)
- [ ] Active improved copy tool (as for all categories)

**Comment by matkoniecz** [comment]
@polly64 

> Change 'Unclassified presumed residential' on dropdown to 'Unclassified presumed non-residential'

So how 'Unclassified presumed residential' would be marked?

> Suggest/implement way of colouring a) Residential garden buildings' and b) Hotels nd adding to the key. We are now able to record these using the dropdowns but we are still not able to visualise them as they are all showing as blue/residential. We need to differentiate in some way

That would require either

(A) changing how colouring works (currently by landuse order) 

or 

(B) moving this group to a new order

**Comment by polly64** [comment]
@matkoniecz @edwardchalstrey1 
Re hotels I think we should classify hotels and guesthouses as Retail as they sell a service. And I think on the key/dropdown we should say 'Retail/Services' not just 'Retail' as they sell a direct service that involves the building . I have had this issue with others such as mechanics workshops. However we need to make a note on NLUD classification hint that some adjustments to NLUD have been made - not sure how best to do this . 

Re garden buildings could we add a pink border around the residential blue for these?

Re changing name for unclassified to add ' unclassified presumed non-residential' is ok?

**Comment by tomalrussell** [comment]
We seem to have a couple of related goals in this (thinking about hotels and residential garden buildings):
- collect data in a standard way for ease of use
- collect additional information of interest to make distinctions that the standard doesn't allow
- present data in a way that works well on our map

We should follow the NLUD classification standard where we collect data on the NLUD classification. Making tweaks to it in-place in our process of data collection, storage and publication, makes it harder to interpret, and harder to use or reuse.

We could add additional fields for more information. E.g. to distinguishing a garden building (and could even imagine some subdivision like garage/shed/office/greenhouse/...). This could be collected in a separate field, and then we can leave the NLUD classification as "Residential, Dwellings" according to the standard "Houses and flats for individuals and families living as a single household, including adjoining garages, gardens, non-thoroughfare service and distribution roads and pathways."

For the land use map presentation, it is possible to combine this data to make a more complicated presentation, with the caveats that it can be harder to read and interpret, and may take more effort to code and maintain.

**Comment by matkoniecz** [comment]
@polly64 

>  Using code from Age data section add a source dropdown in the Current Use section to read as follows:

Is freeform "Source details" supposed to be present?

**Comment by matkoniecz** [comment]
@polly64 

>  Activate verification copy too (as for all categories)

It seems to be present already, or is it supposed to be separately available for autoderived "Current Land Use (Order)"?
