### ISSUE TITLE
2022 TURING PROGRAMME

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#95]
### **Method 1 of 4: Crowdsourcing - Volume data generation, accuracy enhancement, collaborative maintenance**

**Aim**
To harness the vast amount of knowledge/information on the building stock and its dynamic behaviour held within the historic environment sector (HES), and particularly within  memberships of a) national and local amenity/civic societies, b) professional building conservation bodies and c) scholarly publication. To do this to increase data accuracy/coverage esp of building age and lifespan/stock dynamics (required for 3D procedural modelling/energy analysis and to infer many other attribute types) and spatial statistics for the following Colouring London (CL) categories: Typology, Use, Construction, Planning, Team, and Community. To assess the efficiency of this Collaborative Maintenance (CM) model and its creation of a national HES network operating at local (street by street) level producing/overseeing high quality data generation/coverage (for use by Colouring London Research Programme (CRRP) international partners).

**Measurable Objectives/Actions** 
- [X] Set up the Colouring London Historic Environment Advisory group (CLHEAG) with minimum of 10 nationally recognised HES bodies working national and/or regionally scale, with members agreeing to provide a) expert advice and b) marketing to their large memberships/volunteer pools and attend minimum of 2 meetings this year https://github.com/colouring-cities/colouring-london/issues/703. Achieved January 2022. Also waiting feedback from English Heritage and National Trust, and formal confirmation from London Topographic Society.
- [ ] Activate all planned but as yet unimplemented subcategories: for all 12 Colouring London dashboard categories- Location, Land use, Type, Age, Construction, Size, Street Context, Team, Planning, Sustainability, Dynamics, Community (PH/EC/MZ) ro facilitate building attribute data upload in all proposed areas. (Work with @matkoniecz (MZ) and @edwardchalstrey1 (EC) from CL software engineering team) to implement relevant platform features, from existing/new PH briefs). Coordinate new 2022 uploads/verifications from HES volunteers, minimum 200,000 entries by Dec 2022. (Dedicated GitHub issue links for each category to be added) https://github.com/colouring-cities/colouring-london/milestone/14
- [x] colouring-cities/colouring-core#722
- [ ] colouring-cities/colouring-london#100
- [ ] colouring-cities/colouring-london#107
- [x] colouring-cities/colouring-london#105
- [ ] Support HES Marketing campaign. CLHEAG members to recommend engagement with Colouring London to memberships via blogs/newsletters. Status: Due April to be undertaken in collaboration with Turing Comms. Press coverage (PH)
- [ ] Support futureHES collaborative maintenance partnership (CMP) status overseeing and updating data on Type, Age, Use, Construction, Planning, Team, Dynamics and Community through planned 2023 CLHEAG meetings.
- [x] colouring-cities/colouring-core#753
- [ ] Increase awareness of platform through associated national press coverage -min 2 broadsheet or professional journals by Dec 2022 (PH)
- [ ] Secure funding support from HE to advance Listed Building disaggregation and mapping(PH)
- [x] colouring-cities/colouring-core#754
- [ ] Explore potential of working with Turing Comms/Website to improve graphic design/landing page/ 'How to' tools

### **Method 2: Automated data generation using inference**

**Aim**
To build on CL research and demonstrate how specific granular, comprehensive building attribute _draft_ datasets for cities can be  produced, simply and rapidly, using inference providing that access to building age data, and vectorised historical road network data are available. These data can then be checked for accuracy by HES and other CMPs to create accuracy improvement feedback loops. Testing algorithms to identify and geolocate specific building typologies using footprint shape and street networks (historical and current).

**Measurable Objectives/Actions**  
- [ ] colouring-cities/colouring-london#104
- [ ] Use existing age data - crowdsourced (https://colouringlondon.org/view/age`) and automatically generated as above, combined with building footprints, to infer a) roof shape, b) materials, c) construction systems, d) typology descriptions. Produce 3,000,000+ 'draft' data entries in this way, ready for checking by HES and other CMPs
- [ ] Use 18th century vectorised road network data to infer non-domestic building location. Create 75m buffer zones to infer non-domestic buildings along these routes
- [ ] colouring-cities/colouring-london#103
- [ ] To explore potential collaboration with the Turing Urban Grammar initiative https://www.turing.ac.uk/research/research-projects/urban-grammar to exploit existing training data to produce and test city wide draft datasets

### **Method 3: Livestreaming (Planning data/current change)** 

**Aim**
To secure funding for, produce and test a live status planning application visualisation for London.  

**Measurable Objectives/Actions** 
- [X] Support Dr Falli Palaiologou in submission for 50K grant funding EPG Loughborough (PH)
- [ ] Receive funding
- [ ] Implement proposal as ://github.com/colouring-cities/colouring-london/issues/685 (PH/MZ)
- [ ] Test
Subject to funding application being approved

### **Method 4: Bulk open dataset moderation and integration** 
**Aim**
To produce a simple system allowing for submission by users/partners of relevant new bulk open uploads relating to the built and green structure, and integration by the CL software engineering team: a) in relation to OSMM building level polygons, b) to less granular datasets. 

**Measurable Objectives/Actions** 
- [x] colouring-cities/colouring-core#757
- [ ] colouring-cities/colouring-london#101
- [ ]  INSPIRE open land parcel polygons: https://use-land-property-data.service.gov.uk/datasets/inspire/download
- [ ] Flood Risk area: https://data.gov.uk/dataset/7792054a-068d-471b-8969-f53a22b0c9b2/indicative-flood-risk-areas-shapefiles
- [ ] OS OpenMapLocal: streetblock polygons and streets  https://osdatahub.os.uk/downloads/open/OpenMapLocal
- [ ] OS rivers: https://osdatahub.os.uk/downloads/open/OpenRivers)
- [ ] Open Roads: https://osdatahub.os.uk/downloads/open/OpenRoads
- [ ] Green spaces: https://osdatahub.os.uk/downloads/open/OpenGreenspace
- [ ] 2m LIDAR terrain data: https://www.arcgis.com/apps/webappviewer/index.html?id=f765c2a97d644f08927d5cd5abe58d87
- [ ] 9 x historical road vectorised network data 1785-2016 courtesy Dr Kiril Stanilov)
- [ ] ~Explore https://maps.bristol.gov.uk/pinpoint for other relevant datasets
Create links to additional open data sets on Download page 
- [ ] Codepoint Great Britain  https://osdatahub.os.uk/downloads/open/CodePointOpen
- [ ] Open names GB https://osdatahub.os.uk/downloads/open/OpenNames
- [ ] Open identifiers GB: https://osdatahub.os.uk/downloads/open/LIDS
- [ ] Open TOID GB: https://osdatahub.os.uk/downloads/open/OpenTOID
- [ ] Open VectorMapDistrict GB: https://osdatahub.os.uk/downloads/open/VectorMapDistrict
- [ ] - [ ]  England local listings data and conservation area data from Ian Hall (EC)
- [ ] Other relevant OS maps GB 

### 2.0	Colouring Great Britain Research Programme (CGBRP)
**Aim** 
- To scale up the Colouring London prototype to begin an open national census of the building stock to understand what type of buildings exist where (particularly housing) and how well they perform, to improve understanding of future dynamic behaviour and accuracy of modelling, including in relation to negative locked in long-term cycles of demolition/area failure
- To provide a one stop shop for open data on GB building stock
- To set up and support UK regional research institution hubs (as tested in Colouring Australia) to drive regional data upload and verification and to, efficiently, bring together national researcher initiatives relating to stock sustainability and building attribute quality, coverage and accessibility.
- To set up a national partner Collaborative maintenance group/groups  to include Ordnance Survey, The British Geological Society, Historic England, The Royal Institute of British Architects, The Royal Institution of Chartered Surveyors, The Royal Geographical Society and others able/interested in promoting /supporting the Colouring Cities programme through engagement of networks/expert advice
- Work with the Digital Twin Hub (Cambridge) via the DT Community Committee (PH member) and build **Showcase section**** colouring-cities/colouring-core#644 - PH to expand/produce more detailed design. 

**Measurable Objectives/Actions**
- [ ] Integrate OS Master Map polygons for Britain into the Colouring London platform (TR/EC)
- [ ] Set up licence with OS and OS recommended partner (PH) 
- [ ] Upgrade website pages and integrate into main site (PH/EC)
- [ ] Promote Colouring Great Britain (or possibly  could be named ColouringCitiesUK) on Turing Colouring Cities website and GitHub (PH)
- [ ] Set up Colouring Great Britain Research Programme (CGBRP) and record as new GitHub issue to publicly track/share progress (PH)
- [ ] Drive GB public research institutions/Turing collaborations with those interested in  managing regional/country data upload hubs(London managed by Turing). Minimum of two English regions signed up hubs by Dec 2022 (PH). CCRP to offer help in kind on research grants.
- [ ] Build **Showcase section**** colouring-cities/colouring-core#644 - PH to expand/produce more detailed design. Involve discussion with National Digital twin programme re upload of visualisations.
- [ ] Continue work on data ethics in collaboration with DTHub
- [ ] Set up Collaborative Maintenance advisory group for existing national CL partners to drive data accuracy and volume:https://www.pages.colouring.london/whoisinvolved

### 3.0	Colouring Cities Research Programme (CCRP)
**Aim** 
To test Colouring London open code with international partners to collectively produce large-scale, high quality open datasets on the physical composition, dynamic behaviour and performance for use in urban analytics to improve urban quality, resilience and sustainability.  To share knowledge and cooperate on research initiatives relating to stock sustainability. To support the group and share resources and skills (see for example offer of server support for Colouring Lebanon from Colouring Bahrain)

- [ ] Support CCRP international PIs with monthly catch up meetings (PH/FP) (as well as access to new code).
- [ ] Support at least one new CCRP partner funding application with help in kind (PH)
- [ ] Support CCRP international software engineers with regular catch up meetings (TR/EC). TR coordination of monthly catch up meetings (PH/FP) funded via the 2020 Sustainability Fellowship award  https://www.software.ac.uk/about/fellows
- [ ] Produce first draft of open CCRP manual (on GitHub) to support set up and complement Colouring Cities open code, to be co-written with CCRP partners to record hurdles and successes
- [ ] Begin to sketch out at least 2 CCRP collaborative research papers in preparation for 2023
- [x] colouring-cities/colouring-core#760
- [x] colouring-cities/colouring-core#761

Additional work where possible:

- Build mechanism to allow PH simple way of editing site text to also support multidisciplinary working on CCRP research partner platforms. 10. Part of developing methods of increasing non-technical humanities/arts expert input** into code development.

- Build artist's colour key selection gallery for categories -based on MZ idea for adjustable colour key. To increase supportive practise across science, humanities and the arts.

- Begin to look more closely at ISO data standards, particularly with IOER Dresden and other CCRP partners.

- Explore with REG and other SIGs and programmes issues such as  data ethics, and how long-term platform sustainability/collaborative maintenance can be best be achieved.

**Comment by polly64** [comment]
@polly64 to address
